### ISSUE TITLE
Card System: Animations for feedback

### ISSUE THREAD

**Issue by theshark** [The-Sous-Chefs/Cooking-Card-Game#19]
1) When in stun mode, show stun, wait, then switch to enemy turn
2) Show enemy attacks

**Comment by Ian-Thorne** [comment]
Also change existing player attacking animation to not update the backend until the animation ends.

**Comment by Ian-Thorne** [comment]
Probably use Unity Animation Events to delay updating the backend until the animation ends.

**Comment by Ian-Thorne** [comment]
Created some placeholder animations for each of these and implemented both of them, though I'd still like to add some "Your Turn" and "Enemy Turn" animations, and these placeholder animations could be improved so I'm not going to close this issue yet.

**Comment by Ian-Thorne** [comment]
Added some "Your Turn" and "Enemy Turn" animations.
