### ISSUE TITLE
Sorting order for displayed card is incorrect

### ISSUE THREAD

**Issue by theshark** [The-Sous-Chefs/Cooking-Card-Game#22]
Expected Behavior: Card selected in hand should appear closest to player (i.e. should not be partially hidden by other cards).

Current Behavior: Card selected in hand appears in same order as unselected (i.e. is partially hidden by other cards).

**Comment by Ian-Thorne** [comment]
When the player's hand is full the card is still sometimes covered by other cards in their hand
