### ISSUE TITLE
Card information does not fit onto card

### ISSUE THREAD

**Issue by theshark** [The-Sous-Chefs/Cooking-Card-Game#23]
Expected Behavior: all text should fit on the card prefab as would be the case in a physically based card game

Current Behavior: Text overflows outside of card prefab

Suggested fix: Determine the "maximum characters" allowable for each position on the card and ensure all naming schemes and descriptions do not exceed this value.

**Comment by Ian-Thorne** [comment]
Some cards still have this issue
