### ISSUE TITLE
UI Info Cards in Discard Pile does not fit on screen

### ISSUE THREAD

**Issue by theshark** [The-Sous-Chefs/Cooking-Card-Game#24]
Expected Behavior: All information on the Card UI should fit on the screen

Current Behavior: "Cards in your discard pile" element does not fit on screen

![cardindiscardpile](https://user-images.githubusercontent.com/273658/117548359-34f3a680-affa-11eb-846a-90eba32399be.png)

**Comment by DD-1111** [comment]
Changed the anchor setting
![image](https://user-images.githubusercontent.com/56623337/118381525-494d2a00-b61e-11eb-834d-03610449cfdc.png)
