### ISSUE TITLE
Unable to do actions

### ISSUE THREAD

**Issue by theshark** [The-Sous-Chefs/Cooking-Card-Game#25]
Current Behavior: Basic attack, block and restore are grayed out during my turn and I cannot place cards on the board. I am presumably stunned by I see no indication of this.

**Comment by Ian-Thorne** [comment]
Was there anything before that may have caused the issue? There should be a yellow rectangle over the chef's picture when stunned.

**Comment by Ian-Thorne** [comment]
If it was being stunned, then adding animations to the stun to make it more clear and not give the player a turn should fix this issue.

**Comment by Ian-Thorne** [comment]
We've added a new stunned animation to prevent the player from getting into that state, assuming that was the cause, so I'm going to close this.
