### ISSUE TITLE
Cards displayed in hand are not correct

### ISSUE THREAD

**Issue by theshark** [The-Sous-Chefs/Cooking-Card-Game#27]
Current Behavior: Number of cards in hand versus cards displayed in hand is inconsistent. Cards are not being placed on the board even when I drag them.

1) Card 22 and 25 were originally at this position in my hand
2) Dragged cards 22 and 25 to the board
3) Card 22 and 25 moved to the position currently seen in the screenshot

![cardplacementissues](https://user-images.githubusercontent.com/273658/117548790-7f762280-affc-11eb-858a-55ac1f1d6e50.png)

**Comment by Ian-Thorne** [comment]
This issue may be a result of some things not being super clear or intuitive:
  1. When a card is dragged out of the hand but not played, it goes back to the front of the hand
  2. All cards have to be dragged onto an enemy to be played

We could resolve this by not allowing the hand to re-order and only requiring cards that need targets to be dragged onto an enemy (also when holding such a card we should highlight the enemies to make it clear that's where they need to go), then let other cards be dragged anywhere outside of the hand zone.
