### ISSUE TITLE
Implement support for having multiple enemies in the backend card system

### ISSUE THREAD

**Issue by Ian-Thorne** [The-Sous-Chefs/Cooking-Card-Game#5]
Don't worry about setting this up, visually, though. We'll focus on getting 1-v-1 battles playable before worrying about 1-v-many battles being playable.

**Comment by DD-1111** [comment]
maybe can't be finished on time and this does not affect the functionality of a card system, not that high priority.

**Comment by DD-1111** [comment]
Once we have multiple enemies, we will need a target system

**Comment by DD-1111** [comment]
This part is a little bit hard without a UI, so I basically put it with a lower priority
